name: blktests-ci

on:
  pull_request:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: VM start up
        run: |
          echo "Current working directory: ${{ github.workspace }}"
          whoami
          vagrant --version
          vagrant status
